### ISSUE TITLE
Bug: Can't see and manage users of the XRay protocol

### ISSUE THREAD

**Issue by KiGamji** [amnezia-vpn/amnezia-client#902] opened 2024-07-20 11:32 UTC
**Describe the bug**
In the share VPN menu, the "Users" list is empty. It does not show any clients, including the admin sessions, while it works fine for other protocols, such as OpenVPN over Cloak and AmneziaWG

**Screenshots**
XRay (the users list is empty!):
![image](https://github.com/user-attachments/assets/66868f81-2f2c-4c03-b4f3-e7b95443bb61)

OpenVPN over Cloak:
![image](https://github.com/user-attachments/assets/55b97cdf-2805-44e7-859b-79aa358a0a4d)

**Desktop:**
 - OS: Windows 10
 - Version: 4.6.0.3

**Server:**
 - OS: Debian 12

**Comment by mizzuri** [comment] 2024-07-22 05:44
I'm not certain, but isn't it because XRay config is the same for everyone?

**Comment by KiGamji** [comment] 2024-07-22 08:59
@mizzuri 
huh? why can I create and share XRay configs then?

**Comment by mizzuri** [comment] 2024-07-22 10:15
What do you mean?

It's my understanding that you create the config once, and share the same config with others. (Even though you create a new XRay config with a new name, it's still the same.)

I could be totally wrong, though.

**Comment by KiGamji** [comment] 2024-07-22 12:52
@mizzuri it's not the same. create a few configs, and see that the QR Codes/VPN:// strings are different.

**Comment by mizzuri** [comment] 2024-07-23 08:23
> @mizzuri it's not the same. create a few configs, and see that the QR Codes/VPN:// strings are different.

I just did. They're all the same. At least for me.
I created configs using both the Amnezia app format and the XRay native format, and they are identical within their respective formats.

**Comment by mityasun** [comment] 2024-07-24 12:59
I confirm that everything is the same on Android version 4.6.0.3 and on Windows 4.6.0.3:
- There is no user management when using Xray (empty list of users).
- All configs are 100% identical.

**Comment by KiGamji** [comment] 2024-07-24 16:31
I just tried it, and it seems like the configs are identical indeed, if shared from the same admin session. Although they are different, when sharing configs from different admin sessions. 🤷‍♂️

**Comment by Crashermage** [comment] 2024-07-28 18:55
Guys, how can I find the config file for Xray in the Linux file system? Does it even exist?

**Comment by mizzuri** [comment] 2024-07-30 05:11
> Guys, how can I find the config file for Xray in the Linux file system? Does it even exist?

I'm not certain if you can perform that action directly within the file system. Even if it's possible, the item will most likely be encrypted and located within one of the containers.

**Comment by rubbersoul935** [comment] 2024-08-01 11:40
The same issue on Ubuntu 22.04, Debian 12, Debian 11 with Xray.
Can't see the users I've shared the Xray key with.
The Xray shared key is the same every time I try to generate a new one.
Amnezia 4.6.0.3 MacOs / 4.6.0.4 iOS

**Comment by mizzuri** [comment] 2024-08-02 06:05
> The same issue on Ubuntu 22.04, Debian 12, Debian 11 with Xray. Can't see the users I've shared the Xray key with. The Xray shared key is the same every time I try to generate a new one. Amnezia 4.6.0.3 MacOs / 4.6.0.4 iOS

I don't think it's an issue. I think it is by design.

**Comment by KiGamji** [comment] 2024-08-02 06:08
if that would be the case, why would the strings be different on different admin sessions though?

**Comment by Mel0ne** [comment] 2024-08-03 08:02
I confirm, Xray users manage list is empty (on Android and Windows latest release clients).

**Comment by mizzuri** [comment] 2024-08-05 09:41
> if that would be the case, why would the strings be different on different admin sessions though?

I believe the app's GUI and workflows should be updated to provide a clearer experience for users.

**Comment by Nethius** [comment] 2024-08-05 09:56
there is no user management for Xray in the client yet, this functionality is in WIP

**Comment by Nethius** [comment] 2024-08-10 07:02
Xray user management will be in this issue https://github.com/amnezia-vpn/amnezia-client/issues/960

**Closed as completed by Nethius** 2024-08-10 07:02 UTC

**Comment by mammadovhaji** [comment] 2025-01-26 15:34
Checked this future on Windows, Android and iOS v4.8.2.3, unfortunately problem not solved.

**Comment by Webbrother** [comment] 2025-07-13 09:11
Mac OS Sequoia 15.5 (24F74). Client version 4.8.8.3. 
Still no XRay users.

Any updates about it?

**Comment by Detsle** [comment] 2025-07-14 11:27
I am facing the same problem, there is no user management option so far.
