### ISSUE TITLE
Failed to init due to not standard linux shell

### ISSUE THREAD

**Issue by Mishavint** [amnezia-vpn/amnezia-client#1213] opened 2024-10-28 09:44 UTC
**Describe the bug**
Tried to init self-hosted VPN, entered server info and it failed, since root was configured to use fish shell. Fixed after using bash as default shell. 

**To Reproduce**
1. Go to 'Self-hosted VPN'

**Expected behavior**
Hosted vpn

**Smartphone (please complete the following information):**
 - Version [e.g. 2.1.2]

**Server (please complete the following information):**
 - OS: Ubuntu 20.04.6
 - SHELL: fish 3.1.0

**Comment by vanyasem** [comment] 2024-10-29 10:33
The scripts should specify a [shebang](https://en.wikipedia.org/wiki/Shebang_%28Unix%29) `#!/usr/bin/env bash` instead of relying on the default shell

[check_user_in_sudo.sh](https://github.com/amnezia-vpn/amnezia-client/blob/4.8.2.3/client/server_scripts/check_user_in_sudo.sh) fails to get executed on fish shell, resulting in an [Error 205: ServerUserNotInSudo](https://docs.amnezia.org/ru/troubleshooting/error-codes/#error-205-serverusernotinsudo):

```
$ CUR_USER=$(whoami);\
  groups $CUR_USER
fish: Unsupported use of '='. In fish, please use 'set CUR_USER $(whoami)'.
```

**Comment by vanyasem** [comment] 2024-10-29 10:35
Duplicate of https://github.com/amnezia-vpn/amnezia-client/issues/1201

**Closed as not planned** 2024-10-31 06:36 UTC
